spring:
    config:
        import: file:./sidepeek_backend_secret/application-local.yml
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        locations: classpath:db/migration, classpath:db/data
