spring:
    config:
        import: file:./sidepeek_backend_secret/application.yml
    profiles:
        active: local
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

server:
    servlet:
        context-path: /api/v1
