name: SidePeek CI with Gradle

on:
  push:
    branches: [ "chore/**" ]
  # pull_request:
  #   branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Set up MySQL
      uses: samin/mysql-action@v1.3
      with:
        mysql user: ${{ secrets.TEST_DB_USER }}
        mysql password: ${{ secrets.TEST_DB_PASSWORD }}
        mysql database: ${{ secrets.TEST_DB }}
        host port: ${{ secrets.TEST_DB_PORT }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test Jacoco Coverage Report
      id: jacoco
      uses: madrapps/jacoco-report@v1.6
      with:
        title: 📝 Jacoco Test Coverage
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80

    - name: Send Slack Notification
      if: always()
      uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          success_text: 'Build completed successfully'
          failure_text: 'Build failed'
          cancelled_text: 'Build was cancelled'
          fields: |
            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
            { "title": "Branch", "value": "${env.BRANCH}", "short": true },
            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]

